version: '3.8'

services:
  db:
    image: postgres:13-alpine
    env_file:
      - ./.env
    environment:
      # Эти переменные нужны для инициализации PostgreSQL и для healthcheck
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data/
    healthcheck: # Добавляем проверку здоровья для БД
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s # Проверять каждые 5 секунд
      timeout: 5s  # Таймаут для каждой проверки 5 секунд
      retries: 5   # Повторить 5 раз, прежде чем объявить сервис нездоровым

  backend:
    build: ./backend
    env_file:
      - ./.env
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    volumes:
      - static:/app/build/static/ # Если фронтенд генерирует статику
    # ports: # Фронтенд обычно не нужно пробрасывать наружу, если Nginx его проксирует
    #   - "3000:3000" # Если вы хотите напрямую обращаться к фронтенду для отладки

  gateway:
    build: ./nginx
    volumes:
      - static:/var/html/static/
      - media:/var/html/media/
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend # Nginx зависит от обоих, чтобы проксировать запросы

volumes:
  pg_data:
  static:
  media: