version: '3.8'

services:
  db:
    image: postgres:13-alpine # Используем более легковесный образ
    env_file:
      - ./.env
    volumes:
    - pg_data:/var/lib/postgresql/data/
    healthcheck: # Добавляем проверку здоровья для БД
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s # Проверять каждые 5 секунд
      timeout: 5s  # Таймаут для каждой проверки 5 секунд
      retries: 5   # Повторить 5 раз, прежде чем объявить сервис нездоровым
  
  backend:
    build: ./backend
    env_file:
      - ./.env
    volumes:
      - static:/app/static/
      - media:/app/media/
    depends_on:
      - db

  frontend:
    build: ./frontend
    #volumes:
      #- static:/app/build/static/
  
  gateway:
    build: ./nginx
    volumes:
      - static:/var/html/static/
      - media:/var/html/media/
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend # Nginx зависит от обоих, чтобы проксировать запросы

volumes:
  pg_data:
  static:
  media: