server {
  listen 80;
  index index.html;

  location / {
        # Проксирование запросов к фронтенду
        proxy_pass http://frontend:8000; # Или другой порт, если фронтенд на другом
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/ {
        # Проксирование запросов к бэкенду
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /admin/ {
        # Проксирование запросов к админке Django
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /static/ {
        # Раздача статических файлов из volume
        alias /var/html/static/; # Путь внутри контейнера gateway, куда будет смонтирован volume
    }

    location /media/ {
        # Раздача медиафайлов из volume
        alias /var/html/media/; # Путь внутри контейнера gateway, куда будет смонтирован volume
    }
}
